In [2]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
mylist

[1, 2, 3]

In [6]:
type(mylist)

list

In [10]:
myarray = np.array(mylist)

In [11]:
myarray

array([1, 2, 3])

In [12]:
type(myarray)

numpy.ndarray

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(5,21,5)

array([ 5, 10, 15, 20])

In [20]:
np.zeros(shape = (10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
type(0)

int

In [22]:
type(0.0)

float

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [31]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [32]:
arr2 = np.random.randint(20,100,15)

In [33]:
arr2

array([24, 83, 60, 80, 84, 25, 32, 60, 69, 28, 49, 79, 54, 64, 92])

In [34]:
type(arr2)

numpy.ndarray

In [35]:
arr.max()

95

In [36]:
arr.argmax()

0

In [37]:
arr.min()

9

In [38]:
arr.argmin()

7

In [39]:
arr.mean()

60.8

In [41]:
arr.shape

(10,)

In [43]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [46]:
mat = np.arange(1,101).reshape(10,10)

In [47]:
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [48]:
mat[0,0]

1

In [49]:
mat[3,2]

33

In [50]:
mat[:,1]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [51]:
mat[:,5]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [53]:
mat[:,1].reshape(1,10)

array([[ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92]])

In [54]:
mat[:,1].reshape(10,1)

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [55]:
mat[2,:]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
mat[3,3]

34

In [64]:
mat[0:3,0:4]

array([[ 1,  1,  1,  4],
       [ 1,  1,  1, 14],
       [ 1,  1,  1, 24]])

In [58]:
mat[0:10,0:10]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [59]:
mat[0:3,0:3] = 1

In [60]:
mat

array([[  1,   1,   1,   4,   5,   6,   7,   8,   9,  10],
       [  1,   1,   1,  14,  15,  16,  17,  18,  19,  20],
       [  1,   1,   1,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [61]:
mynewmat = mat.copy()

In [62]:
mynewmat

array([[  1,   1,   1,   4,   5,   6,   7,   8,   9,  10],
       [  1,   1,   1,  14,  15,  16,  17,  18,  19,  20],
       [  1,   1,   1,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [66]:
mynewmat[0:6,:] = 999

In [67]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])